package sam.com.findhome;

public class product_showpostMOSTA {
    public int ID;
    public String post_content;
    public String post_title;
    public String guid11;

    public String _noe_melk_moamele; // noe_melk_moamele;
    public String _noe_melk; // _noe_melk;
    public String _moshakhasat_asli_melk_noe_bana_mostagh; // _moshakhasat_asli_melk_noe_bana_mostagh;
    public String _moshakhasat_asli_melk_mosahat_kol_banai_build; // _moshakhasat_asli_melk_mosahat_kol_banai_build;
    public String _moshakhasat_asli_melk_masahat_zamin; // _moshakhasat_asli_melk_masahat_zamin;
    public String _moshakhasat_asli_melk_number_bar; // _moshakhasat_asli_melk_number_bar;
    public String _moshakhasat_asli_melk_sale_build; // _moshakhasat_asli_melk_sale_build;
    public String _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio; // _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;
    public String _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat; // _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;
    public String _price_shrayet_sell_cheng_price_all_sell_cheng; // _price_shrayet_sell_cheng_price_all_sell_cheng;
    public String _price_shrayet_sell_cheng_check_seel_cheng; // _price_shrayet_sell_cheng_check_seel_cheng;
    public String _price_shrayet_sell_cheng_max_money; // _price_shrayet_sell_cheng_max_money;
    public String _price_shrayet_sell_cheng_money_pish_pay; // _price_shrayet_sell_cheng_money_pish_pay;
    public String _price_shrayet_sell_cheng_time_tahvil; // _price_shrayet_sell_cheng_time_tahvil;
    public String _price_shrayet_sell_cheng_mizan_anjam_shode; // _price_shrayet_sell_cheng_mizan_anjam_shode;
    public String _price_shrayet_sell_cheng_mizan_vam; // _price_shrayet_sell_cheng_mizan_vam;
    public String _price_shrayet_sell_cheng_sod_vam; // _price_shrayet_sell_cheng_sod_vam;
    public String _price_shrayet_sell_cheng_number_ghest; // _price_shrayet_sell_cheng_number_ghest;
    public String _price_shrayet_sell_cheng_price_har_ghest; // _price_shrayet_sell_cheng_price_har_ghest;
    public String _price_shrayet_sell_cheng_price_rahn; // _price_shrayet_sell_cheng_price_rahn;
    public String _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_check; // _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_check;
    public String _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_edit; // _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_edit;
    public String _more_joziat_melk_edari_tejari_nama_nama_check; // _more_joziat_melk_edari_tejari_nama_nama_check;
    public String _more_joziat_melk_edari_tejari_nama_nama_edit; // _more_joziat_melk_edari_tejari_nama_nama_edit;
    public String _more_joziat_melk_edari_tejari_eskelet_eskelet_check; // _more_joziat_melk_edari_tejari_eskelet_eskelet_check;
    public String _more_joziat_melk_edari_tejari_eskelet_eskelet_edit; // _more_joziat_melk_edari_tejari_eskelet_eskelet_edit;
    public String _more_joziat_melk_edari_tejari_divar_divar_check; // _more_joziat_melk_edari_tejari_divar_divar_check;
    public String _more_joziat_melk_edari_tejari_divar_divar_edit; // _more_joziat_melk_edari_tejari_divar_divar_edit;
    public String _more_joziat_melk_edari_tejari_coldhot_coldhot_check; // _more_joziat_melk_edari_tejari_coldhot_coldhot_check;
    public String _more_joziat_melk_edari_tejari_coldhot_coldhot_edit; // _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;
    public String _more_joziat_melk_edari_tejari_refahi_refahi_check_mosta; // _more_joziat_melk_edari_tejari_refahi_refahi_check_mosta;
    public String _more_joziat_melk_edari_tejari_refahi_refahi_edit; // _more_joziat_melk_edari_tejari_refahi_refahi_edit;
    public String _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta; // _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta;
    public String _more_joziat_melk_edari_tejari_safe_safe_edit; // _more_joziat_melk_edari_tejari_safe_safe_edit;
    public String _more_joziat_melk_edari_tejari_dastresi_dastresi_check_mosta; // _more_joziat_melk_edari_tejari_dastresi_dastresi_check_mosta;
    public String _more_joziat_melk_edari_tejari_dastresi_dastres_edit; // _more_joziat_melk_edari_tejari_dastresi_dastres_edit;
    public String _more_joziat_melk_edari_tejari_ghozar_asli; // _more_joziat_melk_edari_tejari_ghozar_asli;
    public String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta; // _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;
    public String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit; // _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;
    public String _more_joziat_melk_edari_tejari_sport_sport_check; // _more_joziat_melk_edari_tejari_sport_sport_check;
    public String _more_joziat_melk_edari_tejari_sport_sport_edit; // _more_joziat_melk_edari_tejari_sport_sport_edit;
    public String _more_joziat_melk_edari_tejari_view_view_check; // _more_joziat_melk_edari_tejari_view_view_check;
    public String _more_joziat_melk_edari_tejari_view_view_edit; // _more_joziat_melk_edari_tejari_view_view_edit;
    public String _more_joziat_melk_edari_tejari_tasisat_tasisat_check_mosta; // _more_joziat_melk_edari_tejari_tasisat_tasisat_check_mosta;
    public String _more_joziat_melk_edari_tejari_tasisat_tasisat_edit; // _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;
    public String _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat; // _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;
    public String _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat; // _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;
    public String _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam; // _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;

    public product_showpostMOSTA(int ID, String post_content, String post_title, String guid11

            , String _noe_melk_moamele // noe_melk_moamele;
            , String _noe_melk // _noe_melk;
            , String _moshakhasat_asli_melk_noe_bana_mostagh // _moshakhasat_asli_melk_noe_bana_mostagh;
            , String _moshakhasat_asli_melk_mosahat_kol_banai_build // _moshakhasat_asli_melk_mosahat_kol_banai_build;
            , String _moshakhasat_asli_melk_masahat_zamin // _moshakhasat_asli_melk_masahat_zamin;
            , String _moshakhasat_asli_melk_number_bar // _moshakhasat_asli_melk_number_bar;
            , String _moshakhasat_asli_melk_sale_build // _moshakhasat_asli_melk_sale_build;
            , String _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio // _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;
            , String _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat // _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;
            , String _price_shrayet_sell_cheng_price_all_sell_cheng // _price_shrayet_sell_cheng_price_all_sell_cheng;
            , String _price_shrayet_sell_cheng_check_seel_cheng // _price_shrayet_sell_cheng_check_seel_cheng;
            , String _price_shrayet_sell_cheng_max_money // _price_shrayet_sell_cheng_max_money;
            , String _price_shrayet_sell_cheng_money_pish_pay // _price_shrayet_sell_cheng_money_pish_pay;
            , String _price_shrayet_sell_cheng_time_tahvil // _price_shrayet_sell_cheng_time_tahvil;
            , String _price_shrayet_sell_cheng_mizan_anjam_shode // _price_shrayet_sell_cheng_mizan_anjam_shode;
            , String _price_shrayet_sell_cheng_mizan_vam // _price_shrayet_sell_cheng_mizan_vam;
            , String _price_shrayet_sell_cheng_sod_vam // _price_shrayet_sell_cheng_sod_vam;
            , String _price_shrayet_sell_cheng_number_ghest // _price_shrayet_sell_cheng_number_ghest;
            , String _price_shrayet_sell_cheng_price_har_ghest // _price_shrayet_sell_cheng_price_har_ghest;
            , String _price_shrayet_sell_cheng_price_rahn // _price_shrayet_sell_cheng_price_rahn;
            , String _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_check // _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_check;
            , String _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_edit // _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_edit;
            , String _more_joziat_melk_edari_tejari_nama_nama_check // _more_joziat_melk_edari_tejari_nama_nama_check;
            , String _more_joziat_melk_edari_tejari_nama_nama_edit // _more_joziat_melk_edari_tejari_nama_nama_edit;
            , String _more_joziat_melk_edari_tejari_eskelet_eskelet_check // _more_joziat_melk_edari_tejari_eskelet_eskelet_check;
            , String _more_joziat_melk_edari_tejari_eskelet_eskelet_edit // _more_joziat_melk_edari_tejari_eskelet_eskelet_edit;
            , String _more_joziat_melk_edari_tejari_divar_divar_check // _more_joziat_melk_edari_tejari_divar_divar_check;
            , String _more_joziat_melk_edari_tejari_divar_divar_edit // _more_joziat_melk_edari_tejari_divar_divar_edit;
            , String _more_joziat_melk_edari_tejari_coldhot_coldhot_check // _more_joziat_melk_edari_tejari_coldhot_coldhot_check;
            , String _more_joziat_melk_edari_tejari_coldhot_coldhot_edit // _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;
            , String _more_joziat_melk_edari_tejari_refahi_refahi_check_mosta // _more_joziat_melk_edari_tejari_refahi_refahi_check_mosta;
            , String _more_joziat_melk_edari_tejari_refahi_refahi_edit // _more_joziat_melk_edari_tejari_refahi_refahi_edit;
            , String _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta // _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta;
            , String _more_joziat_melk_edari_tejari_safe_safe_edit // _more_joziat_melk_edari_tejari_safe_safe_edit;
            , String _more_joziat_melk_edari_tejari_dastresi_dastresi_check_mosta // _more_joziat_melk_edari_tejari_dastresi_dastresi_check_mosta;
            , String _more_joziat_melk_edari_tejari_dastresi_dastres_edit // _more_joziat_melk_edari_tejari_dastresi_dastres_edit;
            , String _more_joziat_melk_edari_tejari_ghozar_asli // _more_joziat_melk_edari_tejari_ghozar_asli;
            , String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta // _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;
            , String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit // _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;
            , String _more_joziat_melk_edari_tejari_sport_sport_check // _more_joziat_melk_edari_tejari_sport_sport_check;
            , String _more_joziat_melk_edari_tejari_sport_sport_edit // _more_joziat_melk_edari_tejari_sport_sport_edit;
            , String _more_joziat_melk_edari_tejari_view_view_check // _more_joziat_melk_edari_tejari_view_view_check;
            , String _more_joziat_melk_edari_tejari_view_view_edit // _more_joziat_melk_edari_tejari_view_view_edit;
            , String _more_joziat_melk_edari_tejari_tasisat_tasisat_check_mosta // _more_joziat_melk_edari_tejari_tasisat_tasisat_check_mosta;
            , String _more_joziat_melk_edari_tejari_tasisat_tasisat_edit // _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;
            , String _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat // _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;
            , String _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat // _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;
            , String _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam // _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;

    ) {
        this.ID = ID;
        this.post_content = post_content;
        this.post_title = post_title;
        this.guid11 = guid11;

        this._noe_melk_moamele = _noe_melk_moamele;
        this._noe_melk = _noe_melk;
        this._moshakhasat_asli_melk_noe_bana_mostagh = _moshakhasat_asli_melk_noe_bana_mostagh;
        this._moshakhasat_asli_melk_mosahat_kol_banai_build = _moshakhasat_asli_melk_mosahat_kol_banai_build;
        this._moshakhasat_asli_melk_masahat_zamin = _moshakhasat_asli_melk_masahat_zamin;
        this._moshakhasat_asli_melk_number_bar = _moshakhasat_asli_melk_number_bar;
        this._moshakhasat_asli_melk_sale_build = _moshakhasat_asli_melk_sale_build;
        this._moshakhasat_asli_melk_vaziita_build_vaziita_build_radio = _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;
        this._moshakhasat_asli_melk_vaziita_build_ghabel_sokonat = _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;
        this._price_shrayet_sell_cheng_price_all_sell_cheng = _price_shrayet_sell_cheng_price_all_sell_cheng;
        this._price_shrayet_sell_cheng_check_seel_cheng = _price_shrayet_sell_cheng_check_seel_cheng;
        this._price_shrayet_sell_cheng_max_money = _price_shrayet_sell_cheng_max_money;
        this._price_shrayet_sell_cheng_money_pish_pay = _price_shrayet_sell_cheng_money_pish_pay;
        this._price_shrayet_sell_cheng_time_tahvil = _price_shrayet_sell_cheng_time_tahvil;
        this._price_shrayet_sell_cheng_mizan_anjam_shode = _price_shrayet_sell_cheng_mizan_anjam_shode;
        this._price_shrayet_sell_cheng_mizan_vam = _price_shrayet_sell_cheng_mizan_vam;
        this._price_shrayet_sell_cheng_sod_vam = _price_shrayet_sell_cheng_sod_vam;
        this._price_shrayet_sell_cheng_number_ghest = _price_shrayet_sell_cheng_number_ghest;
        this._price_shrayet_sell_cheng_price_har_ghest = _price_shrayet_sell_cheng_price_har_ghest;
        this._price_shrayet_sell_cheng_price_rahn = _price_shrayet_sell_cheng_price_rahn;
        this._more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_check = _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_check;
        this._more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_edit = _more_joziat_melk_edari_tejari_karbari_pishnahadi_karbari_pishnahadi_edit;
        this._more_joziat_melk_edari_tejari_nama_nama_check = _more_joziat_melk_edari_tejari_nama_nama_check;
        this._more_joziat_melk_edari_tejari_nama_nama_edit = _more_joziat_melk_edari_tejari_nama_nama_edit;
        this._more_joziat_melk_edari_tejari_eskelet_eskelet_check = _more_joziat_melk_edari_tejari_eskelet_eskelet_check;
        this._more_joziat_melk_edari_tejari_eskelet_eskelet_edit = _more_joziat_melk_edari_tejari_eskelet_eskelet_edit;
        this._more_joziat_melk_edari_tejari_divar_divar_check = _more_joziat_melk_edari_tejari_divar_divar_check;
        this._more_joziat_melk_edari_tejari_divar_divar_edit = _more_joziat_melk_edari_tejari_divar_divar_edit;
        this._more_joziat_melk_edari_tejari_coldhot_coldhot_check = _more_joziat_melk_edari_tejari_coldhot_coldhot_check;
        this._more_joziat_melk_edari_tejari_coldhot_coldhot_edit = _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;
        this._more_joziat_melk_edari_tejari_refahi_refahi_check_mosta = _more_joziat_melk_edari_tejari_refahi_refahi_check_mosta;
        this._more_joziat_melk_edari_tejari_refahi_refahi_edit = _more_joziat_melk_edari_tejari_refahi_refahi_edit;
        this._more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta = _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta;
        this._more_joziat_melk_edari_tejari_safe_safe_edit = _more_joziat_melk_edari_tejari_safe_safe_edit;
        this._more_joziat_melk_edari_tejari_dastresi_dastresi_check_mosta = _more_joziat_melk_edari_tejari_dastresi_dastresi_check_mosta;
        this._more_joziat_melk_edari_tejari_dastresi_dastres_edit = _more_joziat_melk_edari_tejari_dastresi_dastres_edit;
        this._more_joziat_melk_edari_tejari_ghozar_asli = _more_joziat_melk_edari_tejari_ghozar_asli;
        this._more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta = _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;
        this._more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit = _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;
        this._more_joziat_melk_edari_tejari_sport_sport_check = _more_joziat_melk_edari_tejari_sport_sport_check;
        this._more_joziat_melk_edari_tejari_sport_sport_edit = _more_joziat_melk_edari_tejari_sport_sport_edit;
        this._more_joziat_melk_edari_tejari_view_view_check = _more_joziat_melk_edari_tejari_view_view_check;
        this._more_joziat_melk_edari_tejari_view_view_edit = _more_joziat_melk_edari_tejari_view_view_edit;
        this._more_joziat_melk_edari_tejari_tasisat_tasisat_check_mosta = _more_joziat_melk_edari_tejari_tasisat_tasisat_check_mosta;
        this._more_joziat_melk_edari_tejari_tasisat_tasisat_edit = _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;
        this._more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat = _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;
        this._more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat = _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;
        this._more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam = _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;

    }
}