package sam.com.findhome;

public class product_showpost {
    public int ID;
    public String post_content;
    public String post_title;
    public String guid11;
    public String _noe_melk_moamele;// _noe_melk_moamele;
    public String _noe_melk;// _noe_melk;
    public String _moshakhasat_asli_melk_noe_bana;// _moshakhasat_asli_melk_noe_bana;
    public String _moshakhasat_asli_melk_masahat_build;// _moshakhasat_asli_melk_masahat_build;
    public String _moshakhasat_asli_melk_masahat_zamin;// _moshakhasat_asli_melk_masahat_zamin;
    public String _moshakhasat_asli_melk_number_room;// _moshakhasat_asli_melk_number_room;
    public String _moshakhasat_asli_melk_number_parking;// _moshakhasat_asli_melk_number_parking;
    public String _moshakhasat_asli_melk_sale_build;// _moshakhasat_asli_melk_sale_build;
    public String _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;// _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;
    public String _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;// _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;
    public String _price_shrayet_sell_cheng_check_seel_cheng;// _price_shrayet_sell_cheng_check_seel_cheng;
    public String _price_shrayet_sell_cheng_max_money;// _price_shrayet_sell_cheng_max_money;
    public String _price_shrayet_sell_cheng_money_pish_pay;// _price_shrayet_sell_cheng_money_pish_pay;
    public String _price_shrayet_sell_cheng_time_tahvil;// _price_shrayet_sell_cheng_time_tahvil;
    public String _price_shrayet_sell_cheng_mizan_anjam_shode;// _price_shrayet_sell_cheng_mizan_anjam_shode;
    public String _price_shrayet_sell_cheng_mizan_vam;// _price_shrayet_sell_cheng_mizan_vam;
    public String _price_shrayet_sell_cheng_sod_vam;// _price_shrayet_sell_cheng_sod_vam;
    public String _price_shrayet_sell_cheng_number_ghest;// _price_shrayet_sell_cheng_number_ghest;
    public String _price_shrayet_sell_cheng_price_har_ghest;// _price_shrayet_sell_cheng_price_har_ghest;
    public String _price_shrayet_sell_cheng_price_rahn;// _price_shrayet_sell_cheng_price_rahn;
    public String _more_joziat_melk_edari_tejari_moghit_build_melk_dar_tabaghe;// _more_joziat_melk_edari_tejari_moghit_build_melk_dar_tabaghe;
    public String _more_joziat_melk_edari_tejari_moghit_build_number_all_tabaghe;// _more_joziat_melk_edari_tejari_moghit_build_number_all_tabaghe;
    public String _more_joziat_melk_edari_tejari_moghit_build_number_vahed_dar_tabaghe;// _more_joziat_melk_edari_tejari_moghit_build_number_vahed_dar_tabaghe;
    public String _more_joziat_melk_edari_tejari_moghit_build_number_all_vahed;// _more_joziat_melk_edari_tejari_moghit_build_number_all_vahed;
    public String _more_joziat_melk_edari_tejari_moghit_build_vaghe_dar_build;// _more_joziat_melk_edari_tejari_moghit_build_vaghe_dar_build;
    public String _more_joziat_melk_edari_tejari_emkanat_vahed_number_anbari;// _more_joziat_melk_edari_tejari_emkanat_vahed_number_anbari;
    public String _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_anbari;// _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_anbari;
    public String _more_joziat_melk_edari_tejari_emkanat_vahed_number_balkon;// _more_joziat_melk_edari_tejari_emkanat_vahed_number_balkon;
    public String _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_kol_balkon;// _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_kol_balkon;
    public String _more_joziat_melk_edari_tejari_wc_wc_irani;// _more_joziat_melk_edari_tejari_wc_wc_irani;
    public String _more_joziat_melk_edari_tejari_wc_wc_us;// _more_joziat_melk_edari_tejari_wc_wc_us;
    public String _more_joziat_melk_edari_tejari_wc_bath;// _more_joziat_melk_edari_tejari_wc_bath;
    public String _more_joziat_melk_edari_tejari_kitchen_kitchen_check;// _more_joziat_melk_edari_tejari_kitchen_kitchen_check;
    public String _more_joziat_melk_edari_tejari_kitchen_kitchen_radio;// _more_joziat_melk_edari_tejari_kitchen_kitchen_radio;
    public String _more_joziat_melk_edari_tejari_kitchen_darai_kabinet;// _more_joziat_melk_edari_tejari_kitchen_darai_kabinet;
    public String _more_joziat_melk_edari_tejari_kitchen_badane_kabinet;// _more_joziat_melk_edari_tejari_kitchen_badane_kabinet;
    public String _more_joziat_melk_edari_tejari_kitchen_safhe_kabinet;// _more_joziat_melk_edari_tejari_kitchen_safhe_kabinet;
    public String _more_joziat_melk_edari_tejari_kitchen_roye_kabinet;// _more_joziat_melk_edari_tejari_kitchen_roye_kabinet;
    public String _more_joziat_melk_edari_tejari_kitchen_tajhizat_kitchen;// _more_joziat_melk_edari_tejari_kitchen_tajhizat_kitchen;
    public String _more_joziat_melk_edari_tejari_kitchen_edit_tozih_kitchen;// _more_joziat_melk_edari_tejari_kitchen_edit_tozih_kitchen;
    public String _more_joziat_melk_edari_tejari_neshiman_neshiman_check;// _more_joziat_melk_edari_tejari_neshiman_neshiman_check;
    public String _more_joziat_melk_edari_tejari_neshiman_neshiman_edit;// _more_joziat_melk_edari_tejari_neshiman_neshiman_edit;
    public String _more_joziat_melk_edari_tejari_shekle_build_radio;// _more_joziat_melk_edari_tejari_shekle_build_radio;
    public String _more_joziat_melk_edari_tejari_nama_nama_check;// _more_joziat_melk_edari_tejari_nama_nama_check;
    public String _more_joziat_melk_edari_tejari_nama_nama_edit;// _more_joziat_melk_edari_tejari_nama_nama_edit;
    public String _more_joziat_melk_edari_tejari_eskelet_eskelet_check;// _more_joziat_melk_edari_tejari_eskelet_eskelet_check;
    public String _more_joziat_melk_edari_tejari_eskelet_eskelet_edit;// ab_more_joziat_melk_edari_tejari_eskelet_eskelet_editcd;
    public String _more_joziat_melk_edari_tejari_kaf_kaf_check;// _more_joziat_melk_edari_tejari_kaf_kaf_check;
    public String _more_joziat_melk_edari_tejari_kaf_kaf_edit;// _more_joziat_melk_edari_tejari_kaf_kaf_edit;
    public String _more_joziat_melk_edari_tejari_divar_divar_check;// _more_joziat_melk_edari_tejari_divar_divar_check;
    public String _more_joziat_melk_edari_tejari_divar_divar_edit;// _more_joziat_melk_edari_tejari_divar_divar_edit;
    public String _more_joziat_melk_edari_tejari_coldhot_coldhot_check;// _more_joziat_melk_edari_tejari_coldhot_coldhot_check;
    public String _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;// _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;
    public String _more_joziat_melk_edari_tejari_refahi_refahi_check;// _more_joziat_melk_edari_tejari_refahi_refahi_check;
    public String _more_joziat_melk_edari_tejari_refahi_refahi_edit;// _more_joziat_melk_edari_tejari_refahi_refahi_edit;
    public String _more_joziat_melk_edari_tejari_safe_safe_check;// _more_joziat_melk_edari_tejari_safe_safe_check;
    public String _more_joziat_melk_edari_tejari_safe_safe_edit;// _more_joziat_melk_edari_tejari_safe_safe_edit;
    public String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;// _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;
    public String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;// _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;
    public String _more_joziat_melk_edari_tejari_sport_sport_check;// _more_joziat_melk_edari_tejari_sport_sport_check;
    public String _more_joziat_melk_edari_tejari_sport_sport_edit;// _more_joziat_melk_edari_tejari_sport_sport_edit;
    public String _more_joziat_melk_edari_tejari_view_view_check;// _more_joziat_melk_edari_tejari_view_view_check;
    public String _more_joziat_melk_edari_tejari_view_view_edit;// _more_joziat_melk_edari_tejari_view_view_edit;
    public String _more_joziat_melk_edari_tejari_nor_nor_check;// _more_joziat_melk_edari_tejari_nor_nor_check;
    public String _more_joziat_melk_edari_tejari_tasisat_tasisat_check;// _more_joziat_melk_edari_tejari_tasisat_tasisat_check;
    public String _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;// _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;
    public String _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;// _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;
    public String _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;// _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;
    public String _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;// _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;
    public String _more_joziat_melk_edari_tejari_safe;// _more_joziat_melk_edari_tejari_safe;
    public String _more_joziat_melk_edari_tejari_emkanatBuild;// _more_joziat_melk_edari_tejari_emkanatBuild;
    public String _more_joziat_melk_edari_tejari_divar;// _more_joziat_melk_edari_tejari_divar;
    public String _more_joziat_melk_edari_tejari_kaf;// _more_joziat_melk_edari_tejari_kaf;
    public String _more_joziat_melk_edari_tejari_shekle_build_check;// _more_joziat_melk_edari_tejari_shekle_build_check;
    public String _more_joziat_melk_edari_tejari_moghit_build;// _more_joziat_melk_edari_tejari_moghit_build;
    public String _price_shrayet;// _price_shrayet;
    public String _price_shrayet_sell_cheng_price_all_sell_cheng;
/*
    public String _more_joziat_melk_edari_tejari_refahi_refahi_check_edari ; // _more_joziat_melk_edari_tejari_refahi_refahi_check_edari;
    public String _more_joziat_melk_edari_tejari_nama_nama_check_edari_tejari ; // _more_joziat_melk_edari_tejari_nama_nama_check_edari_tejari;
    public String _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta ; // _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta;
    public String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_edari ; // _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_edari;
    public String _more_joziat_melk_edari_tejari_tasisat_tasisat_check_edari_tejari ; // _more_joziat_melk_edari_tejari_tasisat_tasisat_check_edari_tejari;
    public String _moshakhasat_asli_melk_vaziita_build_rebuild ; // _moshakhasat_asli_melk_vaziita_build_rebuild;
    public String _more_joziat_melk_edari_tejari_tozih_about_melk ; // _more_joziat_melk_edari_tejari_tozih_about_melk;
    public String _moshakhasat_asli_melk_moghiat_build ; // _moshakhasat_asli_melk_moghiat_build;
*/

    public product_showpost(int ID, String post_content, String post_title, String guid11

            , String _noe_melk_moamele //  _noe_melk_moamele;
            , String _noe_melk //  _noe_melk;
            , String _moshakhasat_asli_melk_noe_bana //  _moshakhasat_asli_melk_noe_bana;
            , String _moshakhasat_asli_melk_masahat_build //  _moshakhasat_asli_melk_masahat_build;
            , String _moshakhasat_asli_melk_masahat_zamin //  _moshakhasat_asli_melk_masahat_zamin;
            , String _moshakhasat_asli_melk_number_room //  _moshakhasat_asli_melk_number_room;
            , String _moshakhasat_asli_melk_number_parking //  _moshakhasat_asli_melk_number_parking;
            , String _moshakhasat_asli_melk_sale_build //  _moshakhasat_asli_melk_sale_build;
            , String _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio //  _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;
            , String _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat //  _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;
            , String _price_shrayet_sell_cheng_check_seel_cheng //  _price_shrayet_sell_cheng_check_seel_cheng;
            , String _price_shrayet_sell_cheng_max_money //  _price_shrayet_sell_cheng_max_money;
            , String _price_shrayet_sell_cheng_money_pish_pay //  _price_shrayet_sell_cheng_money_pish_pay;
            , String _price_shrayet_sell_cheng_time_tahvil //  _price_shrayet_sell_cheng_time_tahvil;
            , String _price_shrayet_sell_cheng_mizan_anjam_shode //  _price_shrayet_sell_cheng_mizan_anjam_shode;
            , String _price_shrayet_sell_cheng_mizan_vam //  _price_shrayet_sell_cheng_mizan_vam;
            , String _price_shrayet_sell_cheng_sod_vam //  _price_shrayet_sell_cheng_sod_vam;
            , String _price_shrayet_sell_cheng_number_ghest //  _price_shrayet_sell_cheng_number_ghest;
            , String _price_shrayet_sell_cheng_price_har_ghest //  _price_shrayet_sell_cheng_price_har_ghest;
            , String _price_shrayet_sell_cheng_price_rahn //  _price_shrayet_sell_cheng_price_rahn;
            , String _more_joziat_melk_edari_tejari_moghit_build_melk_dar_tabaghe //  _more_joziat_melk_edari_tejari_moghit_build_melk_dar_tabaghe;
            , String _more_joziat_melk_edari_tejari_moghit_build_number_all_tabaghe //  _more_joziat_melk_edari_tejari_moghit_build_number_all_tabaghe;
            , String _more_joziat_melk_edari_tejari_moghit_build_number_vahed_dar_tabaghe //  _more_joziat_melk_edari_tejari_moghit_build_number_vahed_dar_tabaghe;
            , String _more_joziat_melk_edari_tejari_moghit_build_number_all_vahed //  _more_joziat_melk_edari_tejari_moghit_build_number_all_vahed;
            , String _more_joziat_melk_edari_tejari_moghit_build_vaghe_dar_build //  _more_joziat_melk_edari_tejari_moghit_build_vaghe_dar_build;
            , String _more_joziat_melk_edari_tejari_emkanat_vahed_number_anbari //  _more_joziat_melk_edari_tejari_emkanat_vahed_number_anbari;
            , String _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_anbari //  _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_anbari;
            , String _more_joziat_melk_edari_tejari_emkanat_vahed_number_balkon //  _more_joziat_melk_edari_tejari_emkanat_vahed_number_balkon;
            , String _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_kol_balkon //  _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_kol_balkon;
            , String _more_joziat_melk_edari_tejari_wc_wc_irani //  _more_joziat_melk_edari_tejari_wc_wc_irani;
            , String _more_joziat_melk_edari_tejari_wc_wc_us //  _more_joziat_melk_edari_tejari_wc_wc_us;
            , String _more_joziat_melk_edari_tejari_wc_bath //  _more_joziat_melk_edari_tejari_wc_bath;
            , String _more_joziat_melk_edari_tejari_kitchen_kitchen_check //  _more_joziat_melk_edari_tejari_kitchen_kitchen_check;
            , String _more_joziat_melk_edari_tejari_kitchen_kitchen_radio //  _more_joziat_melk_edari_tejari_kitchen_kitchen_radio;
            , String _more_joziat_melk_edari_tejari_kitchen_darai_kabinet //  _more_joziat_melk_edari_tejari_kitchen_darai_kabinet;
            , String _more_joziat_melk_edari_tejari_kitchen_badane_kabinet //  _more_joziat_melk_edari_tejari_kitchen_badane_kabinet;
            , String _more_joziat_melk_edari_tejari_kitchen_safhe_kabinet //  _more_joziat_melk_edari_tejari_kitchen_safhe_kabinet;
            , String _more_joziat_melk_edari_tejari_kitchen_roye_kabinet //  _more_joziat_melk_edari_tejari_kitchen_roye_kabinet;
            , String _more_joziat_melk_edari_tejari_kitchen_tajhizat_kitchen //  _more_joziat_melk_edari_tejari_kitchen_tajhizat_kitchen;
            , String _more_joziat_melk_edari_tejari_kitchen_edit_tozih_kitchen //  _more_joziat_melk_edari_tejari_kitchen_edit_tozih_kitchen;
            , String _more_joziat_melk_edari_tejari_neshiman_neshiman_check //  _more_joziat_melk_edari_tejari_neshiman_neshiman_check;
            , String _more_joziat_melk_edari_tejari_neshiman_neshiman_edit //  _more_joziat_melk_edari_tejari_neshiman_neshiman_edit;
            , String _more_joziat_melk_edari_tejari_shekle_build_radio //  _more_joziat_melk_edari_tejari_shekle_build_radio;
            , String _more_joziat_melk_edari_tejari_nama_nama_check //  _more_joziat_melk_edari_tejari_nama_nama_check;
            , String _more_joziat_melk_edari_tejari_nama_nama_edit //  _more_joziat_melk_edari_tejari_nama_nama_edit;
            , String _more_joziat_melk_edari_tejari_eskelet_eskelet_check //  _more_joziat_melk_edari_tejari_eskelet_eskelet_check;
            , String _more_joziat_melk_edari_tejari_eskelet_eskelet_edit //  ab_more_joziat_melk_edari_tejari_eskelet_eskelet_editcd;
            , String _more_joziat_melk_edari_tejari_kaf_kaf_check //  _more_joziat_melk_edari_tejari_kaf_kaf_check;
            , String _more_joziat_melk_edari_tejari_kaf_kaf_edit //  _more_joziat_melk_edari_tejari_kaf_kaf_edit;
            , String _more_joziat_melk_edari_tejari_divar_divar_check //  _more_joziat_melk_edari_tejari_divar_divar_check;
            , String _more_joziat_melk_edari_tejari_divar_divar_edit //  _more_joziat_melk_edari_tejari_divar_divar_edit;
            , String _more_joziat_melk_edari_tejari_coldhot_coldhot_check //  _more_joziat_melk_edari_tejari_coldhot_coldhot_check;
            , String _more_joziat_melk_edari_tejari_coldhot_coldhot_edit //  _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;
            , String _more_joziat_melk_edari_tejari_refahi_refahi_check //  _more_joziat_melk_edari_tejari_refahi_refahi_check;
            , String _more_joziat_melk_edari_tejari_refahi_refahi_edit //  _more_joziat_melk_edari_tejari_refahi_refahi_edit;
            , String _more_joziat_melk_edari_tejari_safe_safe_check //  _more_joziat_melk_edari_tejari_safe_safe_check;
            , String _more_joziat_melk_edari_tejari_safe_safe_edit //  _more_joziat_melk_edari_tejari_safe_safe_edit;
            , String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta //  _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;
            , String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit //  _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;
            , String _more_joziat_melk_edari_tejari_sport_sport_check //  _more_joziat_melk_edari_tejari_sport_sport_check;
            , String _more_joziat_melk_edari_tejari_sport_sport_edit //  _more_joziat_melk_edari_tejari_sport_sport_edit;
            , String _more_joziat_melk_edari_tejari_view_view_check //  _more_joziat_melk_edari_tejari_view_view_check;
            , String _more_joziat_melk_edari_tejari_view_view_edit //  _more_joziat_melk_edari_tejari_view_view_edit;
            , String _more_joziat_melk_edari_tejari_nor_nor_check //  _more_joziat_melk_edari_tejari_nor_nor_check;
            , String _more_joziat_melk_edari_tejari_tasisat_tasisat_check //  _more_joziat_melk_edari_tejari_tasisat_tasisat_check;
            , String _more_joziat_melk_edari_tejari_tasisat_tasisat_edit //  _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;
            , String _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat //  _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;
            , String _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat //  _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;
            , String _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam //  _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;
            , String _more_joziat_melk_edari_tejari_safe //  _more_joziat_melk_edari_tejari_safe;
            , String _more_joziat_melk_edari_tejari_emkanatBuild //  _more_joziat_melk_edari_tejari_emkanatBuild;
            , String _more_joziat_melk_edari_tejari_divar //  _more_joziat_melk_edari_tejari_divar;
            , String _more_joziat_melk_edari_tejari_kaf //  _more_joziat_melk_edari_tejari_kaf;
            , String _more_joziat_melk_edari_tejari_shekle_build_check //  _more_joziat_melk_edari_tejari_shekle_build_check;
            , String _more_joziat_melk_edari_tejari_moghit_build //  _more_joziat_melk_edari_tejari_moghit_build;
            , String _price_shrayet //  _price_shrayet;
            , String _price_shrayet_sell_cheng_price_all_sell_cheng
/*
            ,String _more_joziat_melk_edari_tejari_refahi_refahi_check_edari // _more_joziat_melk_edari_tejari_refahi_refahi_check_edari;
            ,String _more_joziat_melk_edari_tejari_nama_nama_check_edari_tejari // _more_joziat_melk_edari_tejari_nama_nama_check_edari_tejari;
            ,String _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta // _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta;
            ,String _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_edari // _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_edari;
            ,String _more_joziat_melk_edari_tejari_tasisat_tasisat_check_edari_tejari // _more_joziat_melk_edari_tejari_tasisat_tasisat_check_edari_tejari;
            ,String _moshakhasat_asli_melk_vaziita_build_rebuild // _moshakhasat_asli_melk_vaziita_build_rebuild;
            ,String _more_joziat_melk_edari_tejari_tozih_about_melk // _more_joziat_melk_edari_tejari_tozih_about_melk;
            ,String _moshakhasat_asli_melk_moghiat_build // _moshakhasat_asli_melk_moghiat_build;
*/
    ) {
        this.ID = ID;
        this.post_content = post_content;
        this.post_title = post_title;
        this.guid11 = guid11;
        this._noe_melk_moamele = _noe_melk_moamele;
        this._noe_melk = _noe_melk;
        this._moshakhasat_asli_melk_noe_bana = _moshakhasat_asli_melk_noe_bana;
        this._moshakhasat_asli_melk_masahat_build = _moshakhasat_asli_melk_masahat_build;
        this._moshakhasat_asli_melk_masahat_zamin = _moshakhasat_asli_melk_masahat_zamin;
        this._moshakhasat_asli_melk_number_room = _moshakhasat_asli_melk_number_room;
        this._moshakhasat_asli_melk_number_parking = _moshakhasat_asli_melk_number_parking;
        this._moshakhasat_asli_melk_sale_build = _moshakhasat_asli_melk_sale_build;
        this._moshakhasat_asli_melk_vaziita_build_vaziita_build_radio = _moshakhasat_asli_melk_vaziita_build_vaziita_build_radio;
        this._moshakhasat_asli_melk_vaziita_build_ghabel_sokonat = _moshakhasat_asli_melk_vaziita_build_ghabel_sokonat;
        this._price_shrayet_sell_cheng_check_seel_cheng = _price_shrayet_sell_cheng_check_seel_cheng;
        this._price_shrayet_sell_cheng_max_money = _price_shrayet_sell_cheng_max_money;
        this._price_shrayet_sell_cheng_money_pish_pay = _price_shrayet_sell_cheng_money_pish_pay;
        this._price_shrayet_sell_cheng_time_tahvil = _price_shrayet_sell_cheng_time_tahvil;
        this._price_shrayet_sell_cheng_mizan_anjam_shode = _price_shrayet_sell_cheng_mizan_anjam_shode;
        this._price_shrayet_sell_cheng_mizan_vam = _price_shrayet_sell_cheng_mizan_vam;
        this._price_shrayet_sell_cheng_sod_vam = _price_shrayet_sell_cheng_sod_vam;
        this._price_shrayet_sell_cheng_number_ghest = _price_shrayet_sell_cheng_number_ghest;
        this._price_shrayet_sell_cheng_price_har_ghest = _price_shrayet_sell_cheng_price_har_ghest;
        this._price_shrayet_sell_cheng_price_rahn = _price_shrayet_sell_cheng_price_rahn;
        this._more_joziat_melk_edari_tejari_moghit_build_melk_dar_tabaghe = _more_joziat_melk_edari_tejari_moghit_build_melk_dar_tabaghe;
        this._more_joziat_melk_edari_tejari_moghit_build_number_all_tabaghe = _more_joziat_melk_edari_tejari_moghit_build_number_all_tabaghe;
        this._more_joziat_melk_edari_tejari_moghit_build_number_vahed_dar_tabaghe = _more_joziat_melk_edari_tejari_moghit_build_number_vahed_dar_tabaghe;
        this._more_joziat_melk_edari_tejari_moghit_build_number_all_vahed = _more_joziat_melk_edari_tejari_moghit_build_number_all_vahed;
        this._more_joziat_melk_edari_tejari_moghit_build_vaghe_dar_build = _more_joziat_melk_edari_tejari_moghit_build_vaghe_dar_build;
        this._more_joziat_melk_edari_tejari_emkanat_vahed_number_anbari = _more_joziat_melk_edari_tejari_emkanat_vahed_number_anbari;
        this._more_joziat_melk_edari_tejari_emkanat_vahed_masahat_anbari = _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_anbari;
        this._more_joziat_melk_edari_tejari_emkanat_vahed_number_balkon = _more_joziat_melk_edari_tejari_emkanat_vahed_number_balkon;
        this._more_joziat_melk_edari_tejari_emkanat_vahed_masahat_kol_balkon = _more_joziat_melk_edari_tejari_emkanat_vahed_masahat_kol_balkon;
        this._more_joziat_melk_edari_tejari_wc_wc_irani = _more_joziat_melk_edari_tejari_wc_wc_irani;
        this._more_joziat_melk_edari_tejari_wc_wc_us = _more_joziat_melk_edari_tejari_wc_wc_us;
        this._more_joziat_melk_edari_tejari_wc_bath = _more_joziat_melk_edari_tejari_wc_bath;
        this._more_joziat_melk_edari_tejari_kitchen_kitchen_check = _more_joziat_melk_edari_tejari_kitchen_kitchen_check;
        this._more_joziat_melk_edari_tejari_kitchen_kitchen_radio = _more_joziat_melk_edari_tejari_kitchen_kitchen_radio;
        this._more_joziat_melk_edari_tejari_kitchen_darai_kabinet = _more_joziat_melk_edari_tejari_kitchen_darai_kabinet;
        this._more_joziat_melk_edari_tejari_kitchen_badane_kabinet = _more_joziat_melk_edari_tejari_kitchen_badane_kabinet;
        this._more_joziat_melk_edari_tejari_kitchen_safhe_kabinet = _more_joziat_melk_edari_tejari_kitchen_safhe_kabinet;
        this._more_joziat_melk_edari_tejari_kitchen_roye_kabinet = _more_joziat_melk_edari_tejari_kitchen_roye_kabinet;
        this._more_joziat_melk_edari_tejari_kitchen_tajhizat_kitchen = _more_joziat_melk_edari_tejari_kitchen_tajhizat_kitchen;
        this._more_joziat_melk_edari_tejari_kitchen_edit_tozih_kitchen = _more_joziat_melk_edari_tejari_kitchen_edit_tozih_kitchen;
        this._more_joziat_melk_edari_tejari_neshiman_neshiman_check = _more_joziat_melk_edari_tejari_neshiman_neshiman_check;
        this._more_joziat_melk_edari_tejari_neshiman_neshiman_edit = _more_joziat_melk_edari_tejari_neshiman_neshiman_edit;
        this._more_joziat_melk_edari_tejari_shekle_build_radio = _more_joziat_melk_edari_tejari_shekle_build_radio;
        this._more_joziat_melk_edari_tejari_nama_nama_check = _more_joziat_melk_edari_tejari_nama_nama_check;
        this._more_joziat_melk_edari_tejari_nama_nama_edit = _more_joziat_melk_edari_tejari_nama_nama_edit;
        this._more_joziat_melk_edari_tejari_eskelet_eskelet_check = _more_joziat_melk_edari_tejari_eskelet_eskelet_check;
        this._more_joziat_melk_edari_tejari_eskelet_eskelet_edit = _more_joziat_melk_edari_tejari_eskelet_eskelet_edit;
        this._more_joziat_melk_edari_tejari_kaf_kaf_check = _more_joziat_melk_edari_tejari_kaf_kaf_check;
        this._more_joziat_melk_edari_tejari_kaf_kaf_edit = _more_joziat_melk_edari_tejari_kaf_kaf_edit;
        this._more_joziat_melk_edari_tejari_divar_divar_check = _more_joziat_melk_edari_tejari_divar_divar_check;
        this._more_joziat_melk_edari_tejari_divar_divar_edit = _more_joziat_melk_edari_tejari_divar_divar_edit;
        this._more_joziat_melk_edari_tejari_coldhot_coldhot_check = _more_joziat_melk_edari_tejari_coldhot_coldhot_check;
        this._more_joziat_melk_edari_tejari_coldhot_coldhot_edit = _more_joziat_melk_edari_tejari_coldhot_coldhot_edit;
        this._more_joziat_melk_edari_tejari_refahi_refahi_check = _more_joziat_melk_edari_tejari_refahi_refahi_check;
        this._more_joziat_melk_edari_tejari_refahi_refahi_edit = _more_joziat_melk_edari_tejari_refahi_refahi_edit;
        this._more_joziat_melk_edari_tejari_safe_safe_check = _more_joziat_melk_edari_tejari_safe_safe_check;
        this._more_joziat_melk_edari_tejari_safe_safe_edit = _more_joziat_melk_edari_tejari_safe_safe_edit;
        this._more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta = _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_mosta;
        this._more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit = _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_edit;
        this._more_joziat_melk_edari_tejari_sport_sport_check = _more_joziat_melk_edari_tejari_sport_sport_check;
        this._more_joziat_melk_edari_tejari_sport_sport_edit = _more_joziat_melk_edari_tejari_sport_sport_edit;
        this._more_joziat_melk_edari_tejari_view_view_check = _more_joziat_melk_edari_tejari_view_view_check;
        this._more_joziat_melk_edari_tejari_view_view_edit = _more_joziat_melk_edari_tejari_view_view_edit;
        this._more_joziat_melk_edari_tejari_nor_nor_check = _more_joziat_melk_edari_tejari_nor_nor_check;
        this._more_joziat_melk_edari_tejari_tasisat_tasisat_check = _more_joziat_melk_edari_tejari_tasisat_tasisat_check;
        this._more_joziat_melk_edari_tejari_tasisat_tasisat_edit = _more_joziat_melk_edari_tejari_tasisat_tasisat_edit;
        this._more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat = _more_joziat_melk_edari_tejari_moshakhasat_sanad_malekiat;
        this._more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat = _more_joziat_melk_edari_tejari_moshakhasat_sanad_noe_malekiat;
        this._more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam = _more_joziat_melk_edari_tejari_moshakhasat_sanad_sanad_dar_dast_eghdam;
        this._more_joziat_melk_edari_tejari_safe = _more_joziat_melk_edari_tejari_safe;
        this._more_joziat_melk_edari_tejari_emkanatBuild = _more_joziat_melk_edari_tejari_emkanatBuild;
        this._more_joziat_melk_edari_tejari_divar = _more_joziat_melk_edari_tejari_divar;
        this._more_joziat_melk_edari_tejari_kaf = _more_joziat_melk_edari_tejari_kaf;
        this._more_joziat_melk_edari_tejari_shekle_build_check = _more_joziat_melk_edari_tejari_shekle_build_check;
        this._more_joziat_melk_edari_tejari_moghit_build = _more_joziat_melk_edari_tejari_moghit_build;
        this._price_shrayet = _price_shrayet;
        this._price_shrayet_sell_cheng_price_all_sell_cheng = _price_shrayet_sell_cheng_price_all_sell_cheng;
/*
        this._more_joziat_melk_edari_tejari_refahi_refahi_check_edari = _more_joziat_melk_edari_tejari_refahi_refahi_check_edari;
        this._more_joziat_melk_edari_tejari_nama_nama_check_edari_tejari = _more_joziat_melk_edari_tejari_nama_nama_check_edari_tejari;
        this._more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta = _more_joziat_melk_edari_tejari_safe_safe_check_edari_mosta;
        this._more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_edari = _more_joziat_melk_edari_tejari_emkanatBuild_emkanatBuild_check_edari;
        this._more_joziat_melk_edari_tejari_tasisat_tasisat_check_edari_tejari = _more_joziat_melk_edari_tejari_tasisat_tasisat_check_edari_tejari;
        this._moshakhasat_asli_melk_vaziita_build_rebuild = _moshakhasat_asli_melk_vaziita_build_rebuild;
        this._more_joziat_melk_edari_tejari_tozih_about_melk = _more_joziat_melk_edari_tejari_tozih_about_melk;
        this._moshakhasat_asli_melk_moghiat_build = _moshakhasat_asli_melk_moghiat_build;
*/
    }
}